{
  "type": "issue",
  "issue": {
    "id": 284375960,
    "node_id": "MDU6SXNzdWUyODQzNzU5NjA=",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/12011",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/12011/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/12011/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/12011/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/12011",
    "number": 12011,
    "state": "closed",
    "state_reason": "completed",
    "title": "bitcoind writes files to current working dir instead of default data dir when access to other data dir in bitcoin.conf is not permitted",
    "body": "## Description\r\n\r\nI compiled bitcoin from source (tag v0.15.1), created a `bitcoin.conf` in `/home/myuser/.bitcoin` and in the configuration file I unintentionally configured a `datadir` directory didn't exist and whose parent directory ownership was set to `root:root` because I previously had to mount it with `sudo`.\r\n\r\nWhen running `bitcoind -printtoconsole` an error message was shown similar to https://github.com/bitcoin/bitcoin/issues/11825, basically saying that bitcoind didn't have permissions for the configured directory.\r\n\r\nNow instead of writing the files (`blocks` and `chainstate` directories, as well as the files `db.log`, `debug.log`, `fee_estimates.dat`, `.lock` and `wallet.dat`) to the default data directory (`/home/myuser/.bitcoin`), the files were written to the current working directory.\r\n\r\nI'd expect the files to be written to the default datadir if the configured datadir doesn't have the correct permissions.\r\n\r\n## Further info\r\n\r\n`bitcoin.conf`:\r\n\r\n```\r\nrpcuser=<redacted>\r\nrpcpassword=<redacted>\r\ndatadir=/mnt/path/to/bitcoin\r\ntxindex=1\r\n```\r\n\r\nOutput when running `bitcoind -printtoconsole` while the configured datadir has the wrong permissions (the many newlines are part of the actual output):\r\n\r\n```\r\nmyuser@myhost:~/some/path$ bitcoind -printtoconsole\r\n2017-12-24 18:05:29\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n2017-12-24 18:05:29 Bitcoin version v0.15.1\r\n2017-12-24 18:05:29 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1\r\n2017-12-24 18:05:29 Assuming ancestors of block 0000000000000000003b9ce759c2a087d52abc4266f8f4ebd6d768b89defa50a have valid signatures.\r\n2017-12-24 18:05:29 Setting nMinimumChainWork=000000000000000000000000000000000000000000723d3581fe1bd55373540a\r\n2017-12-24 18:05:29 Using the 'standard' SHA256 implementation\r\n2017-12-24 18:05:29 Using RdRand as an additional entropy source\r\n2017-12-24 18:05:29 Default data directory /home/myuser/.bitcoin\r\n2017-12-24 18:05:29 Using data directory\r\n2017-12-24 18:05:29 Using config file bitcoin.conf\r\n2017-12-24 18:05:29 Using at most 125 automatic connections (1024 file descriptors available)\r\n2017-12-24 18:05:29 Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements\r\n2017-12-24 18:05:29 Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements\r\n2017-12-24 18:05:29 Using 4 threads for script verification\r\n2017-12-24 18:05:29 scheduler thread start\r\n2017-12-24 18:05:29 HTTP: creating work queue of depth 16\r\n2017-12-24 18:05:29 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.\r\n2017-12-24 18:05:29 HTTP: starting 4 worker threads\r\n2017-12-24 18:05:29 init message: Verifying wallet(s)...\r\n2017-12-24 18:05:29 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)\r\n2017-12-24 18:05:29 Using wallet wallet.dat\r\n2017-12-24 18:05:29 CDBEnv::Open: LogDir=database ErrorFile=db.log\r\n2017-12-24 18:05:29 Cache configuration:\r\n2017-12-24 18:05:29 * Using 56.2MiB for block index database\r\n2017-12-24 18:05:29 * Using 8.0MiB for chain state database\r\n2017-12-24 18:05:29 * Using 385.8MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)\r\n2017-12-24 18:05:29 init message: Loading block index...\r\n2017-12-24 18:05:29 Opening LevelDB in blocks/index\r\n2017-12-24 18:05:29 Opened LevelDB successfully\r\n2017-12-24 18:05:29 Using obfuscation key for blocks/index: 0000000000000000\r\n2017-12-24 18:05:29 LoadBlockIndexDB: last block file = 0\r\n2017-12-24 18:05:29 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=0, size=0, heights=0...0, time=1970-01-01...1970-01-01)\r\n2017-12-24 18:05:29 Checking all blk files are present...\r\n2017-12-24 18:05:29 LoadBlockIndexDB: transaction index enabled\r\n2017-12-24 18:05:29 Initializing databases...\r\n2017-12-24 18:05:29 Opening LevelDB in chainstate\r\n2017-12-24 18:05:29 Opened LevelDB successfully\r\n2017-12-24 18:05:29 Using obfuscation key for chainstate: <redacted>\r\n2017-12-24 18:05:29 init message: Rewinding blocks...\r\n2017-12-24 18:05:29  block index               9ms\r\n2017-12-24 18:05:29 init message: Loading wallet...\r\n2017-12-24 18:05:29 nFileVersion = 150100\r\n2017-12-24 18:05:29 Keys: 2002 plaintext, 0 encrypted, 2002 w/ metadata, 2002 total\r\n2017-12-24 18:05:29  wallet                   58ms\r\n2017-12-24 18:05:29 setKeyPool.size() = 2000\r\n2017-12-24 18:05:29 mapWallet.size() = 0\r\n2017-12-24 18:05:29 mapAddressBook.size() = 1\r\n2017-12-24 18:05:29\r\n\r\n************************\r\nEXCEPTION: N5boost10filesystem16filesystem_errorE\r\nboost::filesystem::space: Operation not permitted\r\nbitcoin in AppInit()\r\n\r\n\r\n\r\n************************\r\nEXCEPTION: N5boost10filesystem16filesystem_errorE\r\nboost::filesystem::space: Operation not permitted\r\nbitcoin in AppInit()\r\n\r\n2017-12-24 18:05:29 scheduler thread interrupt\r\n2017-12-24 18:05:29 Shutdown: In progress...\r\n2017-12-24 18:05:29 *** System error while flushing: boost::filesystem::space: Operation not permitted\r\n2017-12-24 18:05:29 Error: Error: A fatal internal error occurred, see debug.log for details\r\nError: Error: A fatal internal error occurred, see debug.log for details\r\n2017-12-24 18:05:29 *** System error while flushing: boost::filesystem::space: Operation not permitted\r\n2017-12-24 18:05:29 Error: Error: A fatal internal error occurred, see debug.log for details\r\nError: Error: A fatal internal error occurred, see debug.log for details\r\n2017-12-24 18:05:29 Shutdown: done\r\n```",
    "user": {
      "login": "philippgille",
      "id": 170670,
      "node_id": "MDQ6VXNlcjE3MDY3MA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/170670?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/philippgille",
      "html_url": "https://github.com/philippgille",
      "followers_url": "https://api.github.com/users/philippgille/followers",
      "following_url": "https://api.github.com/users/philippgille/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/philippgille/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/philippgille/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/philippgille/subscriptions",
      "organizations_url": "https://api.github.com/users/philippgille/orgs",
      "repos_url": "https://api.github.com/users/philippgille/repos",
      "events_url": "https://api.github.com/users/philippgille/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/philippgille/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [],
    "assignees": [],
    "author_association": "NONE",
    "locked": true,
    "active_lock_reason": "resolved",
    "comments": 1,
    "closed_at": "2018-09-06T02:24:38Z",
    "created_at": "2017-12-24T18:10:39Z",
    "updated_at": "2021-09-08T12:38:52Z"
  },
  "events": [
    {
      "event": "commented",
      "id": 377980538,
      "node_id": "MDEyOklzc3VlQ29tbWVudDM3Nzk4MDUzOA==",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/377980538",
      "actor": {
        "login": "jnewbery",
        "id": 1063656,
        "node_id": "MDQ6VXNlcjEwNjM2NTY=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1063656?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jnewbery",
        "html_url": "https://github.com/jnewbery",
        "followers_url": "https://api.github.com/users/jnewbery/followers",
        "following_url": "https://api.github.com/users/jnewbery/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/jnewbery/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/jnewbery/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/jnewbery/subscriptions",
        "organizations_url": "https://api.github.com/users/jnewbery/orgs",
        "repos_url": "https://api.github.com/users/jnewbery/repos",
        "events_url": "https://api.github.com/users/jnewbery/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/jnewbery/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2018-04-02T17:07:06Z",
      "updated_at": "2018-04-02T17:07:06Z",
      "author_association": "MEMBER",
      "body": "I can't reproduce this. When I configure `datadir` to be a directory that I don't have permissions for, I see the same exceptions as you:\r\n\r\n```\r\n2018-04-02T17:01:29Z \r\n\r\n************************\r\nEXCEPTION: N5boost10filesystem16filesystem_errorE       \r\nboost::filesystem::create_directory: Permission denied: \"/home/ubuntu/fakebitcoin/blocks\"       \r\nbitcoin in AppInit()       \r\n\r\n\r\n\r\n************************\r\nEXCEPTION: N5boost10filesystem16filesystem_errorE       \r\nboost::filesystem::create_directory: Permission denied: \"/home/ubuntu/fakebitcoin/blocks\"       \r\nbitcoin in AppInit()       \r\n\r\n2018-04-02T17:01:29Z Shutdown: In progress...\r\n2018-04-02T17:01:29Z DeleteAuthCookie: Unable to remove random auth cookie file: boost::filesystem::create_directory: Permission denied: \"/home/ubuntu/fakebitcoin/regtest\"\r\n2018-04-02T17:01:29Z Shutdown: Unable to remove pidfile: boost::filesystem::remove: Permission denied: \"/home/ubuntu/fakebitcoin/regtest/bitcoind.pid\"\r\n2018-04-02T17:01:29Z Shutdown: done\r\n```\r\n\r\nHowever, I don't see any of the files you see in my local directory (and I can't really see how they would be - the `boost::filesystem::space: Operation not permitted` error happens before `AppInitMain`, so I don't see how those files could have been written).\r\n\r\nA couple of questions:\r\n\r\n- are you sure those files weren't sitting around from before?\r\n- are you still able to reproduce this? Are you able to reproduce on v0.16?",
      "user": {
        "login": "jnewbery",
        "id": 1063656,
        "node_id": "MDQ6VXNlcjEwNjM2NTY=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1063656?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jnewbery",
        "html_url": "https://github.com/jnewbery",
        "followers_url": "https://api.github.com/users/jnewbery/followers",
        "following_url": "https://api.github.com/users/jnewbery/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/jnewbery/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/jnewbery/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/jnewbery/subscriptions",
        "organizations_url": "https://api.github.com/users/jnewbery/orgs",
        "repos_url": "https://api.github.com/users/jnewbery/repos",
        "events_url": "https://api.github.com/users/jnewbery/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/jnewbery/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/12011#issuecomment-377980538",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/12011"
    },
    {
      "event": "closed",
      "id": 1829322593,
      "node_id": "MDExOkNsb3NlZEV2ZW50MTgyOTMyMjU5Mw==",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/1829322593",
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2018-09-06T02:24:38Z"
    },
    {
      "event": "locked",
      "id": 5272037182,
      "node_id": "LOE_lADOABII584Q8zuYzwAAAAE6POc-",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/5272037182",
      "actor": {
        "login": "DrahtBot",
        "id": 39886733,
        "node_id": "MDQ6VXNlcjM5ODg2NzMz",
        "avatar_url": "https://avatars.githubusercontent.com/u/39886733?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/DrahtBot",
        "html_url": "https://github.com/DrahtBot",
        "followers_url": "https://api.github.com/users/DrahtBot/followers",
        "following_url": "https://api.github.com/users/DrahtBot/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/DrahtBot/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/DrahtBot/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/DrahtBot/subscriptions",
        "organizations_url": "https://api.github.com/users/DrahtBot/orgs",
        "repos_url": "https://api.github.com/users/DrahtBot/repos",
        "events_url": "https://api.github.com/users/DrahtBot/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/DrahtBot/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2021-09-08T12:38:52Z",
      "lock_reason": "resolved"
    }
  ]
}