{
  "type": "issue",
  "issue": {
    "id": 1456692082,
    "node_id": "I_kwDOABII585W01ty",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/26537",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/26537/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/26537/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/26537/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/26537",
    "number": 26537,
    "state": "closed",
    "state_reason": "completed",
    "title": "Multiple connections to same i2p address",
    "body": "<!-- This issue tracker is only for technical issues related to Bitcoin Core.\r\n\r\nGeneral bitcoin questions and/or support requests are best directed to the Bitcoin StackExchange at https://bitcoin.stackexchange.com.\r\n\r\nFor reporting security issues, please read instructions at https://bitcoincore.org/en/contact/.\r\n\r\nIf the node is \"stuck\" during sync or giving \"block checksum mismatch\" errors, please ensure your hardware is stable by running memtest and observe CPU temperature with a load-test tool such as linpack before creating an issue! -->\r\n\r\n<!-- Describe the issue -->\r\n\r\nThis behavior is okay for ipv4 based on https://bitcoin.stackexchange.com/questions/87739/can-a-bitcoin-node-create-an-outgoing-connection-to-a-inbound-node\r\n\r\nHowever, making multiple connections to same i2p peer makes no sense IMO\r\n\r\n**Expected behavior**\r\n\r\nNo connections (outbound/inbound) should be initiated with i2p address that already exists as one of the peer.\r\n\r\n**Actual behavior**\r\n\r\n![image](https://user-images.githubusercontent.com/94559964/202874210-8e2a6d27-6516-4e13-9b89-73ae19893f03.png)\r\n\r\n![Screenshot 2022-11-20 035027](https://user-images.githubusercontent.com/94559964/202874219-21d48a2f-9ceb-4f29-9003-d8ad63de0a6c.png)\r\n\r\n\r\n**To reproduce**\r\n\r\n- Setup 3 nodes such that node2 and node3 works with i2p\r\n- Connect node2 manually with `addnode` in config to node1\r\n- Connect node3 manually with node2 using i2p address\r\n- Observe result for `getpeerinfo` in a few minutes or check peers list in bitcoin-qt\r\n\r\n**System information**\r\n\r\nBitcoin Core Master Branch, v24.0rc2 and v24.0rc4\r\n",
    "user": {
      "login": "ghost",
      "id": 10137,
      "node_id": "MDQ6VXNlcjEwMTM3",
      "avatar_url": "https://avatars.githubusercontent.com/u/10137?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ghost",
      "html_url": "https://github.com/ghost",
      "followers_url": "https://api.github.com/users/ghost/followers",
      "following_url": "https://api.github.com/users/ghost/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/ghost/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/ghost/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
      "organizations_url": "https://api.github.com/users/ghost/orgs",
      "repos_url": "https://api.github.com/users/ghost/repos",
      "events_url": "https://api.github.com/users/ghost/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/ghost/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 64585,
        "node_id": "MDU6TGFiZWw2NDU4NQ==",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug",
        "name": "Bug",
        "color": "FBBAAB",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "NONE",
    "locked": false,
    "comments": 5,
    "closed_at": "2022-11-26T19:49:25Z",
    "created_at": "2022-11-19T22:46:47Z",
    "updated_at": "2022-11-26T19:49:25Z"
  },
  "events": [
    {
      "event": "labeled",
      "id": 7850379711,
      "node_id": "LE_lADOABII585W01tyzwAAAAHT60m_",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/7850379711",
      "actor": null,
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-11-19T22:46:47Z",
      "label": {
        "name": "Bug",
        "color": "FBBAAB"
      }
    },
    {
      "event": "commented",
      "id": 1325086601,
      "node_id": "IC_kwDOABII585O-zeJ",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1325086601",
      "actor": {
        "login": "vasild",
        "id": 266751,
        "node_id": "MDQ6VXNlcjI2Njc1MQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/266751?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/vasild",
        "html_url": "https://github.com/vasild",
        "followers_url": "https://api.github.com/users/vasild/followers",
        "following_url": "https://api.github.com/users/vasild/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/vasild/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/vasild/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/vasild/subscriptions",
        "organizations_url": "https://api.github.com/users/vasild/orgs",
        "repos_url": "https://api.github.com/users/vasild/repos",
        "events_url": "https://api.github.com/users/vasild/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/vasild/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-11-23T13:43:05Z",
      "updated_at": "2022-11-23T13:43:05Z",
      "author_association": "MEMBER",
      "body": "There are is already a check to avoid connecting to an already connected address. See:\r\n\r\nhttps://github.com/bitcoin/bitcoin/issues/22559#issuecomment-903851322 and\r\nhttps://bitcoin.stackexchange.com/a/116097/129003\r\n\r\nWhat you are observing is probably due to the race in that check described above. For the second screenshot I guess what happened is that while you initiated the manual connection, after the connection attempt started, but before it completed an automatic outbound was initiated to the same address and later that address connected to us for the inbound :disappointed:. This is not I2P specific, but more likely to be seen with I2P because establishing a connection takes longer.\r\n\r\nWhat I think can be improved:\r\n\r\n* After accepting an incoming connection, drop it if we already have a connection to the same address (ignore the port).\r\n* Fix the race by maintaining a list of \"attempting to connect to\" addresses and do not initiate more connections to them.\r\n* Or maybe, periodically, e.g. every 5 minutes, check for duplicates in `CConnman::m_nodes` and drop the redundant ones, maybe ignoring the port.",
      "user": {
        "login": "vasild",
        "id": 266751,
        "node_id": "MDQ6VXNlcjI2Njc1MQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/266751?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/vasild",
        "html_url": "https://github.com/vasild",
        "followers_url": "https://api.github.com/users/vasild/followers",
        "following_url": "https://api.github.com/users/vasild/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/vasild/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/vasild/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/vasild/subscriptions",
        "organizations_url": "https://api.github.com/users/vasild/orgs",
        "repos_url": "https://api.github.com/users/vasild/repos",
        "events_url": "https://api.github.com/users/vasild/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/vasild/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/26537#issuecomment-1325086601",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/26537"
    },
    {
      "event": "commented",
      "id": 1326229242,
      "node_id": "IC_kwDOABII585PDKb6",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1326229242",
      "actor": {
        "login": "vasild",
        "id": 266751,
        "node_id": "MDQ6VXNlcjI2Njc1MQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/266751?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/vasild",
        "html_url": "https://github.com/vasild",
        "followers_url": "https://api.github.com/users/vasild/followers",
        "following_url": "https://api.github.com/users/vasild/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/vasild/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/vasild/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/vasild/subscriptions",
        "organizations_url": "https://api.github.com/users/vasild/orgs",
        "repos_url": "https://api.github.com/users/vasild/repos",
        "events_url": "https://api.github.com/users/vasild/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/vasild/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-11-24T10:09:00Z",
      "updated_at": "2022-11-24T10:09:00Z",
      "author_association": "MEMBER",
      "body": "Preventing incoming connections from an address we already have a connection to could block legit cases where multiple distinct nodes run behind a common address. At first I thought that this is ok, since the disconnected node will find another random peer to connect to. But then, having multiple connections with the same address, even if it is the same node, is a minor issue too. Maybe not worth the effort to change that. Or do only for I2P.",
      "user": {
        "login": "vasild",
        "id": 266751,
        "node_id": "MDQ6VXNlcjI2Njc1MQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/266751?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/vasild",
        "html_url": "https://github.com/vasild",
        "followers_url": "https://api.github.com/users/vasild/followers",
        "following_url": "https://api.github.com/users/vasild/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/vasild/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/vasild/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/vasild/subscriptions",
        "organizations_url": "https://api.github.com/users/vasild/orgs",
        "repos_url": "https://api.github.com/users/vasild/repos",
        "events_url": "https://api.github.com/users/vasild/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/vasild/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/26537#issuecomment-1326229242",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/26537"
    },
    {
      "event": "commented",
      "id": 1326815282,
      "node_id": "IC_kwDOABII585PFZgy",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1326815282",
      "actor": {
        "login": "ghost",
        "id": 10137,
        "node_id": "MDQ6VXNlcjEwMTM3",
        "avatar_url": "https://avatars.githubusercontent.com/u/10137?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ghost",
        "html_url": "https://github.com/ghost",
        "followers_url": "https://api.github.com/users/ghost/followers",
        "following_url": "https://api.github.com/users/ghost/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ghost/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ghost/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
        "organizations_url": "https://api.github.com/users/ghost/orgs",
        "repos_url": "https://api.github.com/users/ghost/repos",
        "events_url": "https://api.github.com/users/ghost/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ghost/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-11-24T20:21:01Z",
      "updated_at": "2022-11-24T20:22:00Z",
      "author_association": "NONE",
      "body": ">  For the second screenshot I guess what happened is that while you initiated the manual connection, after the connection attempt started, but before it completed an automatic outbound was initiated to the same address and later that address connected to us for the inbound 😞\r\n\r\nI will try to reproduce this with `deubg=net` although I agree something similar happened as you described.",
      "user": {
        "login": "ghost",
        "id": 10137,
        "node_id": "MDQ6VXNlcjEwMTM3",
        "avatar_url": "https://avatars.githubusercontent.com/u/10137?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ghost",
        "html_url": "https://github.com/ghost",
        "followers_url": "https://api.github.com/users/ghost/followers",
        "following_url": "https://api.github.com/users/ghost/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ghost/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ghost/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
        "organizations_url": "https://api.github.com/users/ghost/orgs",
        "repos_url": "https://api.github.com/users/ghost/repos",
        "events_url": "https://api.github.com/users/ghost/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ghost/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/26537#issuecomment-1326815282",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/26537"
    },
    {
      "event": "commented",
      "id": 1326815701,
      "node_id": "IC_kwDOABII585PFZnV",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1326815701",
      "actor": {
        "login": "ghost",
        "id": 10137,
        "node_id": "MDQ6VXNlcjEwMTM3",
        "avatar_url": "https://avatars.githubusercontent.com/u/10137?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ghost",
        "html_url": "https://github.com/ghost",
        "followers_url": "https://api.github.com/users/ghost/followers",
        "following_url": "https://api.github.com/users/ghost/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ghost/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ghost/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
        "organizations_url": "https://api.github.com/users/ghost/orgs",
        "repos_url": "https://api.github.com/users/ghost/repos",
        "events_url": "https://api.github.com/users/ghost/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ghost/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-11-24T20:21:51Z",
      "updated_at": "2022-11-24T20:21:51Z",
      "author_association": "NONE",
      "body": "> Fix the race by maintaining a list of \"attempting to connect to\" addresses and do not initiate more connections to them.\r\n\r\nThis makes sense.",
      "user": {
        "login": "ghost",
        "id": 10137,
        "node_id": "MDQ6VXNlcjEwMTM3",
        "avatar_url": "https://avatars.githubusercontent.com/u/10137?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ghost",
        "html_url": "https://github.com/ghost",
        "followers_url": "https://api.github.com/users/ghost/followers",
        "following_url": "https://api.github.com/users/ghost/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ghost/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ghost/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
        "organizations_url": "https://api.github.com/users/ghost/orgs",
        "repos_url": "https://api.github.com/users/ghost/repos",
        "events_url": "https://api.github.com/users/ghost/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ghost/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/26537#issuecomment-1326815701",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/26537"
    },
    {
      "event": "commented",
      "id": 1328104066,
      "node_id": "IC_kwDOABII585PKUKC",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1328104066",
      "actor": {
        "login": "ghost",
        "id": 10137,
        "node_id": "MDQ6VXNlcjEwMTM3",
        "avatar_url": "https://avatars.githubusercontent.com/u/10137?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ghost",
        "html_url": "https://github.com/ghost",
        "followers_url": "https://api.github.com/users/ghost/followers",
        "following_url": "https://api.github.com/users/ghost/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ghost/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ghost/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
        "organizations_url": "https://api.github.com/users/ghost/orgs",
        "repos_url": "https://api.github.com/users/ghost/repos",
        "events_url": "https://api.github.com/users/ghost/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ghost/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-11-26T19:49:25Z",
      "updated_at": "2022-11-26T19:49:25Z",
      "author_association": "NONE",
      "body": "> > For the second screenshot I guess what happened is that while you initiated the manual connection, after the connection attempt started, but before it completed an automatic outbound was initiated to the same address and later that address connected to us for the inbound 😞\r\n> \r\n> I will try to reproduce this with `deubg=net` although I agree something similar happened as you described.\r\n\r\nIssue is intermittent and I couldn't collect any useful logs. ",
      "user": {
        "login": "ghost",
        "id": 10137,
        "node_id": "MDQ6VXNlcjEwMTM3",
        "avatar_url": "https://avatars.githubusercontent.com/u/10137?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ghost",
        "html_url": "https://github.com/ghost",
        "followers_url": "https://api.github.com/users/ghost/followers",
        "following_url": "https://api.github.com/users/ghost/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ghost/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ghost/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
        "organizations_url": "https://api.github.com/users/ghost/orgs",
        "repos_url": "https://api.github.com/users/ghost/repos",
        "events_url": "https://api.github.com/users/ghost/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ghost/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/26537#issuecomment-1328104066",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/26537"
    },
    {
      "event": "closed",
      "id": 7896658072,
      "node_id": "CE_lADOABII585W01tyzwAAAAHWrXCY",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/7896658072",
      "actor": null,
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-11-26T19:49:25Z"
    }
  ]
}